const body = document.querySelector('body')
const header = document.createElement('header')
const main = document.createElement('main')
const footer = document.createElement('footer')
const side1 = document.createElement('div')
side1.classList.add('side1')
const side2 = document.createElement('div')
side2.classList.add('side2')
const game = document.createElement('section')
const hero = document.createElement('div')
hero.classList.add('hero')
const gridContainer = document.createElement('div')
gridContainer.classList.add('grid-container')
const grid = document.createElement('.grid')
grid.classList.add('grid')
const rules = document.createElement('a')
const credits = document.createElement('a')

body.append(header)
body.append(main)
body.append(footer)
main.append(side1)
main.append(game)
main.append(side2)
game.append(hero)
game.append(gridContainer)
gridContainer.append(grid)
footer.append(rules)
footer.append(credits)